services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - sqlite_data:/app/db 
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=h1yy%q6*c*k+ek+4jqquz-xd^ms_(=xsm3=o58@t9048tk29qe
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=api.settings
      - ALLOWED_HOSTS=*
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - CORS_ALLOWED_CREDENTIALS=True

  
volumes:
  sqlite_data:
