import {
  FaCode,
  FaDatabase,
  FaMobileAlt,
  FaServer,
  FaCloud,
  FaProjectDiagram,
  FaBullhorn,
  FaBusinessTime,
  FaMoneyBillWave,
  FaUserTie,
  FaTools,
} from "react-icons/fa";
import { MdSecurity, MdBrush } from "react-icons/md";
import { GiArtificialIntelligence, GiSkills } from "react-icons/gi";
import { AiOutlineCopy } from "react-icons/ai";

export const skills = {
  frontend: [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Vue.js",
    "Angular",
    "SASS",
    "LESS",
    "Bootstrap",
    "Tailwind CSS",
    "TypeScript",
    "NPM",
    "Redux",
    "jQuery",
    "Next.js",
    "Nuxt.js",
    "Webpack",
    "Gulp",
    "Figma",
    "Adobe XD",
  ],
  backend: [
    "Python",
    "Java",
    "Django",
    "Flask",
    "Node.js",
    "Express.js",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "Spring Boot",
    "ASP.NET Core",
    "C#",
    "C++",
    "Go",
    "Rust",
    "Kotlin",
    "Scala",
    "Elixir",
    "REST API",
    "Microservices",
    "Serverless",
  ],
  database: [
    "SQL",
    "NoSQL",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "Oracle DB",
    "SQLite",
    "Firebase",
    "DynamoDB",
    "Cassandra",
    "Redis",
    "Elasticsearch",
    "CouchDB",
    "GraphQL (Hasura)",
    "Amazon RDS",
    "Google Cloud Firestore",
    "BigQuery",
    "Data Warehousing",
  ],
  mobile: [
    "Swift",
    "Kotlin",
    "Flutter",
    "React Native",
    "Objective-C",
    "Java (Android)",
    "iOS Development",
    "Android Development",
    "Dart",
    "Xamarin",
    "Unity3D (C#)",
    "ARKit",
    "Ionic",
    "Cordova",
    "PhoneGap",
    "Mobile UI Design",
    "Game Development",
  ],
  devops: [
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud",
    "CI/CD",
    "Jenkins",
    "GitLab CI",
    "Terraform",
    "Ansible",
    "Puppet",
    "Chef",
    "Nginx",
    "Apache",
    "Bash Scripting",
    "Linux System Administration",
    "Windows Server Administration",
    "Networking",
    "Cybersecurity",
    "Monitoring (Prometheus, Grafana)",
    "Infrastructure as Code (IaC)",
    "Containerization",
    "Virtualization",
    "Scripting (Python, Shell)",
  ],
  data_science: [
    "Python (Pandas, NumPy)",
    "R",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Data Visualization (Matplotlib, Seaborn)",
    "Data Analysis",
    "Big Data",
    "Apache Spark",
    "Hadoop",
    "Data Mining",
    "Natural Language Processing (NLP)",
    "Computer Vision",
    "Statistical Analysis",
    "SQL for Data Science",
    "Scikit-learn",
    "Jupyter Notebooks",
    "Mathematical Modeling",
    "Time Series Analysis",
    "Data Wrangling",
  ],
  cybersecurity: [
    "Network Security",
    "Penetration Testing",
    "Ethical Hacking",
    "Cryptography",
    "Threat Analysis",
    "Vulnerability Assessment",
    "Incident Response",
    "Firewalls",
    "Intrusion Detection Systems (IDS)",
    "Security Information and Event Management (SIEM)",
    "Security Auditing",
    "Identity and Access Management (IAM)",
    "Cybersecurity Frameworks (NIST, ISO)",
    "Security Awareness Training",
    "Endpoint Protection",
    "Cloud Security",
    "Data Encryption",
    "Compliance (GDPR, HIPAA)",
    "Risk Management",
    "Forensics",
  ],
  AI_ML: [
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Neural Networks",
    "Computer Vision",
    "Natural Language Processing (NLP)",
    "Reinforcement Learning",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "OpenCV",
    "Generative Adversarial Networks (GANs)",
    "Machine Learning Operations (MLOps)",
    "AutoML",
    "Bayesian Networks",
    "AI Ethics",
    "Robotics",
    "Speech Recognition",
    "Image Recognition",
    "Recommendation Systems",
  ],
  cloud: [
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "Cloud Architecture",
    "Serverless Computing",
    "Infrastructure as a Service (IaaS)",
    "Platform as a Service (PaaS)",
    "Software as a Service (SaaS)",
    "Cloud Security",
    "Cloud Databases",
    "DevOps in the Cloud",
    "Cloud Automation",
    "Cloud Storage (S3, Google Cloud Storage)",
    "Kubernetes in the Cloud",
    "Load Balancing",
    "Elasticity and Scalability",
    "Cost Optimization in the Cloud",
    "Cloud Networking",
    "Hybrid Cloud",
    "Multi-cloud Strategy",
  ],
  project_management: [
    "Agile",
    "Scrum",
    "Kanban",
    "Project Planning",
    "Risk Management",
    "Stakeholder Management",
    "Resource Management",
    "Team Leadership",
    "Communication Skills",
    "Time Management",
    "Budgeting",
    "Scheduling",
    "Project Tracking",
    "Quality Assurance",
    "Change Management",
    "Conflict Resolution",
    "Decision Making",
    "Project Documentation",
    "JIRA",
    "Confluence",
    "Trello",
    "Asana",
    "MS Project",
  ],
  graphic_design: [
    "Adobe Photoshop",
    "Adobe Illustrator",
    "CorelDRAW",
    "Sketch",
    "Figma",
    "InDesign",
    "Affinity Designer",
    "UI/UX Design",
    "Logo Design",
    "Brand Identity",
    "Typography",
    "Color Theory",
    "Layout Design",
    "Print Design",
    "Digital Illustration",
    "3D Modeling",
    "Motion Graphics",
    "Adobe After Effects",
    "Blender",
    "Cinema 4D",
    "Character Design",
    "Storyboard Creation",
  ],
  copywriting: [
    "SEO Writing",
    "Content Creation",
    "Blog Writing",
    "Technical Writing",
    "Creative Writing",
    "Email Marketing",
    "Social Media Content",
    "Sales Copy",
    "Product Descriptions",
    "Proofreading",
    "Editing",
    "Brand Messaging",
    "Scriptwriting",
    "White Papers",
    "Case Studies",
    "Press Releases",
    "Newsletters",
    "Ghostwriting",
    "Copyediting",
    "Grant Writing",
    "Content Strategy",
    "Speech Writing",
  ],
  digital_marketing: [
    "SEO",
    "Content Marketing",
    "Social Media Marketing",
    "Email Marketing",
    "PPC Advertising",
    "Google Ads",
    "Facebook Ads",
    "Instagram Marketing",
    "LinkedIn Marketing",
    "Influencer Marketing",
    "Affiliate Marketing",
    "Conversion Rate Optimization (CRO)",
    "Marketing Analytics",
    "Google Analytics",
    "Content Strategy",
    "Brand Management",
    "Video Marketing",
    "Growth Hacking",
    "Marketing Automation",
    "E-commerce Marketing",
    "Campaign Management",
    "Copywriting for Marketing",
  ],
  business_analysis: [
    "Business Process Modeling",
    "Requirements Gathering",
    "SWOT Analysis",
    "Stakeholder Analysis",
    "Gap Analysis",
    "Market Research",
    "Business Strategy",
    "Financial Analysis",
    "Cost-Benefit Analysis",
    "Use Case Development",
    "Feasibility Studies",
    "Risk Management",
    "Agile Methodologies",
    "Data Analysis",
    "Microsoft Excel",
    "Power BI",
    "Tableau",
    "Business Intelligence",
    "Change Management",
    "Project Management",
    "Wireframing",
    "Prototyping",
  ],
  finance: [
    "Accounting",
    "Financial Analysis",
    "Budgeting",
    "Forecasting",
    "Financial Modeling",
    "Tax Preparation",
    "Payroll Management",
    "Bookkeeping",
    "Auditing",
    "QuickBooks",
    "SAP FICO",
    "Oracle Financials",
    "Financial Reporting",
    "Investment Analysis",
    "Risk Management",
    "Portfolio Management",
    "Corporate Finance",
    "Mergers & Acquisitions",
    "Financial Planning",
    "Cost Accounting",
    "International Finance",
  ],
  hr_recruitment: [
    "Talent Acquisition",
    "Employee Onboarding",
    "HR Management",
    "Recruitment Strategies",
    "Performance Management",
    "Employee Relations",
    "HRIS Systems",
    "Payroll Processing",
    "Training & Development",
    "Compensation & Benefits",
    "Organizational Development",
    "Labor Law Compliance",
    "Diversity & Inclusion",
    "Employee Engagement",
    "Succession Planning",
    "Conflict Resolution",
    "HR Analytics",
    "Remote Hiring",
    "Interviewing",
    "Candidate Screening",
    "HR Policy Development",
  ],
  other: [
    "Virtual Assistance",
    "Customer Service",
    "Salesforce",
    "CRM Management",
    "Data Entry",
    "Transcription",
    "Legal Writing",
    "Translation Services",
    "Voiceover",
    "Video Editing",
    "Podcast Production",
    "Web Research",
    "E-commerce Support",
    "Dropshipping",
    "Amazon FBA",
    "Shopify",
    "WordPress",
    "Event Planning",
    "Travel Planning",
    "Personal Finance",
    "Real Estate",
    "Operations Management",
    "Supply Chain Management",
    "Logistics",
  ],
};

export const iconMap = {
  frontend: <FaCode />,
  backend: <FaServer />,
  database: <FaDatabase />,
  mobile: <FaMobileAlt />,
  devops: <FaTools />,
  data_science: <GiSkills />,
  cybersecurity: <MdSecurity />,
  AI_ML: <GiArtificialIntelligence />,
  cloud: <FaCloud />,
  project_management: <FaProjectDiagram />,
  graphic_design: <MdBrush />,
  copywriting: <AiOutlineCopy />,
  digital_marketing: <FaBullhorn />,
  business_analysis: <FaBusinessTime />,
  finance: <FaMoneyBillWave />,
  hr_recruitment: <FaUserTie />,
  other: <FaTools />,
};

