const skillSuggestions: string[] = [
  // Programming & Tech
  'JavaScript',
  'TypeScript',
  'React',
  'Next.js',
  'Node.js',
  'Python',
  'Django',
  'Flask',
  'Ruby on Rails',
  'Java',
  'C#',
  'C++',
  'Go',
  'Rust',
  'Kotlin',
  'Swift',
  'SQL',
  'GraphQL',
  'REST API',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'Google Cloud',
  'Machine Learning',
  'Deep Learning',
  'Data Science',
  'TensorFlow',
  'PyTorch',
  'DevOps',
  'CI/CD',
  'Microservices',
  'Blockchain',
  'Cybersecurity',
  'Ethical Hacking',
  'SEO',

  // Design & Creative
  'UI Design',
  'UX Design',
  'Graphic Design',
  'Adobe Photoshop',
  'Adobe Illustrator',
  'Figma',
  'Sketch',
  '3D Modeling',
  'Animation',
  'Video Editing',
  'Motion Graphics',
  'Photography',
  'Copywriting',
  'Content Creation',

  // Marketing & Business
  'Digital Marketing',
  'Social Media Marketing',
  'Email Marketing',
  'Affiliate Marketing',
  'Google Analytics',
  'Project Management',
  'Agile Methodology',
  'Scrum',
  'Product Management',
  'Sales',
  'Business Strategy',
  'Financial Analysis',
  'Accounting',
  'Customer Support',

  // Soft Skills & Other
  'Public Speaking',
  'Leadership',
  'Teamwork',
  'Time Management',
  'Creative Writing',
  'Research',
  'Language Translation',
  'Teaching',
  'Coaching',
  'Negotiation',
  'Critical Thinking',

  // Emerging & Niche
  'Virtual Reality',
  'Augmented Reality',
  'Internet of Things',
  'Quantum Computing',
  'Voice UI',
  'Chatbot Development',
  'Game Development',
  'Mobile App Development',
  'E-commerce',
]

export default skillSuggestions
