const socialDomains: Record<string, string> = {
  website: 'https://yourwebsite.com',
  github: 'https://github.com/yourusername',
  gitlab: 'https://gitlab.com/yourusername',
  bitbucket: 'https://bitbucket.org/yourusername',
  linkedin: 'https://www.linkedin.com/in/yourusername',
  twitch: 'https://www.twitch.tv/yourusername',
  x: 'https://x.com/yourusername',
  upwork: 'https://www.upwork.com/freelancers/~yourprofile',
  freelancer: 'https://www.freelancer.com/u/yourusername',
  toptal: 'https://www.toptal.com/resume/yourusername',
  facebook: 'https://www.facebook.com/yourusername',
  instagram: 'https://www.instagram.com/yourusername',
  vimeo: 'https://vimeo.com/yourusername',
  youtube: 'https://www.youtube.com/channel/yourchannelid',
  pinterest: 'https://www.pinterest.com/yourusername',
  medium: 'https://medium.com/@yourusername',
  tiktok: 'https://www.tiktok.com/@yourusername',
  discord: 'https://discord.gg/yourinvitecode',
  telegram: 'https://t.me/yourusername',
  substack: 'https://yourusername.substack.com',
  gumroad: 'https://yourusername.gumroad.com',
  reddit: 'https://www.reddit.com/user/yourusername',
  stackoverflow: 'https://stackoverflow.com/users/youruserid/yourusername',
  dribbble: 'https://dribbble.com/yourusername',
  behance: 'https://www.behance.net/yourusername',
  slack: 'https://yourworkspace.slack.com',
  soundcloud: 'https://soundcloud.com/yourusername',
  spotify: 'https://open.spotify.com/user/yourusername',
  apple: 'https://podcasts.apple.com/yourusername',
  other: 'https://yourdomain.com',
}

export default socialDomains
