# Generated by Django 5.1.7 on 2025-04-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[("traditional", "Traditional"), ("exchange", "Exchange")],
                default="traditional",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
