# Generated by Django 5.1.7 on 2025-05-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_request_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="estimated_duration",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposed_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
