# Generated by Django 5.1.7 on 2025-05-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_project_estimated_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="expected_delivery",
            field=models.IntegerField(default=0),
        ),
    ]
