# Generated by Django 5.1.7 on 2025-05-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_proposal_expected_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="request_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
