# Generated by Django 5.1.7 on 2025-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="skills",
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.JSONField(
                blank=True, default=list, help_text="List of required skills", null=True
            ),
        ),
    ]
