# Generated by Django 5.1.7 on 2025-05-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_remove_project_skills_project_skills"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
    ]
