# Generated by Django 5.1.7 on 2025-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("community", "Community"),
                            ("skill mastery", "Skill Mastery"),
                            ("elite", "Elite "),
                        ],
                        default="starter",
                        max_length=20,
                    ),
                ),
                ("image", models.URLField()),
            ],
            options={
                "verbose_name": "Badge",
                "verbose_name_plural": "Badges",
                "ordering": ["name"],
            },
        ),
    ]
