# Generated by Django 5.2 on 2025-04-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email is already registered."},
                max_length=254,
                unique=True,
            ),
        ),
    ]
