# Generated by Django 5.1.7 on 2025-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_remove_project_skills_project_skills"),
        ("users", "0004_customuser_credit_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="usereducation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userworkexperience",
            name="user",
        ),
        migrations.AddField(
            model_name="customuser",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("expert", "Expert"),
                ],
                default="beginner",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="availability",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("remote", "Remote"),
                    ("flexible", "Flexible"),
                    ("not_available", "Not Available"),
                ],
                default="full_time",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Skill",
        ),
        migrations.AddField(
            model_name="customuser",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.DeleteModel(
            name="UserEducation",
        ),
        migrations.DeleteModel(
            name="UserWorkExperience",
        ),
    ]
