# Generated by Django 5.1.7 on 2025-05-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_customuser_skills_remove_usereducation_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country_code",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
