# Generated by Django 5.1.7 on 2025-05-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="social_links",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
