# Generated by Django 5.1.7 on 2025-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_customuser_social_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("image", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="social_links",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Social media links in JSON format",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="badges",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="users.badge"
            ),
        ),
    ]
