# Generated by Django 5.1.7 on 2025-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_badge_alter_customuser_social_links_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="group",
            field=models.CharField(
                choices=[
                    ("starter", "Starter"),
                    ("community", "Community"),
                    ("skill mastery", "Skill Mastery"),
                    ("elite", "Elite "),
                ],
                default="starter",
                max_length=20,
            ),
        ),
    ]
