# Generated by Django 5.1.7 on 2025-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0001_initial"),
        ("users", "0009_badge_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Badge",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="badges",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="badges.badge"
            ),
        ),
    ]
