POST http://127.0.0.1:8000/users/register/
Content-Type: application/json

{"first_name":"zack", "last_name": "white","password":"Pass1234", "password2":"Pass1234", "email":"zack123456@gmail.com"}

###

POST http://127.0.0.1:8000/users/token/
Content-Type: application/json

{"email":"mrado372002@gmail.com", "password":"mrado372002="}

###

POST http://127.0.0.1:8000/users/token/
Content-Type: application/json

{"email":"mrado372002@gmail.com", "password":"mrado372002="}

###


PATCH  http://127.0.0.1:8000/users/2/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NzQ5MDE0LCJpYXQiOjE3NDYxNDQyMTQsImp0aSI6ImRmMDY4ZmVkY2E1NjQzNDE4YmVkZDBmNzNiZWZjYWY2IiwidXNlcl9pZCI6MiwiZW1haWwiOiJ6YWNrMTIzNDU2QGdtYWlsLmNvbSIsImlzX3N0YWZmIjpmYWxzZSwiZmlyc3RfbmFtZSI6IkpvaG4iLCJsYXN0X25hbWUiOiJ3aGl0ZSJ9.tBdfta2Jn21j5zuax_sqayUKJd7mkgO8PScTghJK_W4

{
  "experiences": [
    {
        "company": "Test Corp",
        "position": "Developer",
        "start_date": "2020-01-01",
        "end_date": "2022-01-01",
        "description": "Worked on projects"
    }
  ]
}

###
GET http://127.0.0.1:8000/projects/
Content-Type: application/json

{}


PATCH http://127.0.0.1:8000/projects/1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2ODU0NjgyLCJpYXQiOjE3NDYyNDk4ODIsImp0aSI6IjBiZGYyODQ2MzQwMzQ5YmJhYTRlMjVjOGUyYWJiMjMwIiwidXNlcl9pZCI6MSwiZW1haWwiOiJtcmFkbzM3MjAwMkBnbWFpbC5jb20iLCJpc19zdGFmZiI6dHJ1ZSwiZmlyc3RfbmFtZSI6IkFkaGFtIiwibGFzdF9uYW1lIjoiRW1hbSJ9.rW7SJ1WNBcC5WxcYkn5ufNPGoaeGDFPyI3awE93Yo-c

{"assign_to": 1}

###

POST http://127.0.0.1:8000/reviews/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4MDM5OTM4LCJpYXQiOjE3NDc0MzUxMzgsImp0aSI6ImJkZDE4ODdjOTk3OTQwODhhMTIzOTQxNzg1MDcxMGMzIiwidXNlcl9pZCI6MSwiZW1haWwiOiJtcmFkbzM3MjAwMkBnbWFpbC5jb20iLCJpc19zdGFmZiI6dHJ1ZSwiZmlyc3RfbmFtZSI6IkFkaGFtIiwibGFzdF9uYW1lIjoiRW1hbSJ9.BRC9ZkGRPmwakwlr9Zcna7xOABLMIKE0jYtmo5W7wNU


{"project": 1, "rating": 5, "comment": "Excellent work!"}